# Generated by Django 4.1.4 on 2025-06-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=80)),
                ('uniqueid', models.CharField(max_length=100, unique=True)),
                ('view', models.CharField(max_length=4)),
                ('specimenid', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
            ],
            options={
                'verbose_name': 'training entry',
                'verbose_name_plural': 'Training Database',
            },
        ),
        migrations.CreateModel(
            name='ValidClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'allowed genus/species',
                'verbose_name_plural': 'Classes used for training',
            },
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='knownspecies',
            options={'verbose_name_plural': 'Known Species'},
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='caudal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caudal_image', to='port_inspector_app.image'),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='dorsal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dorsal_image', to='port_inspector_app.image'),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='final_identification',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='frontal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontal_image', to='port_inspector_app.image'),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='in_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='lateral_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lateral_image', to='port_inspector_app.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_usda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
