# Generated by Django 4.1.4 on 2025-07-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0002_trainingdatabase_validclasses_alter_genus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name': 'genus link', 'verbose_name_plural': 'Genera Links'},
        ),
        migrations.AlterModelOptions(
            name='knownspecies',
            options={'verbose_name': 'species link', 'verbose_name_plural': 'Species Links'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_special_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='validclasses',
            unique_together={('genus', 'species')},
        ),
    ]
