# Generated by Django 5.2.3 on 2025-09-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0003_alter_genus_options_alter_knownspecies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validclasses',
            options={'ordering': ['genus', 'species'], 'verbose_name': 'allowed genus/species', 'verbose_name_plural': 'Classes used for training'},
        ),
    ]
