# Generated by Django 4.1.4 on 2025-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0004_alter_validclasses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenupload',
            name='failed_views',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='genus_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='genus_uncertainty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='redis_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='species_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='species_uncertainty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='task_status',
            field=models.CharField(default='COMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
