# Generated by Django 4.1.4 on 2025-06-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0005_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=80)),
                ('uniqueid', models.CharField(max_length=100, unique=True)),
                ('view', models.CharField(max_length=4)),
                ('specimenid', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
            ],
        ),
    ]
