# Generated by Django 4.1.4 on 2025-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0005_specimenupload_failed_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimenupload',
            name='genus_confidence_label',
            field=models.CharField(default='Uncertain', max_length=30),
        ),
        migrations.AddField(
            model_name='specimenupload',
            name='species_confidence_label',
            field=models.CharField(default='Uncertain', max_length=30),
        ),
    ]
