# Generated by Django 4.1.4 on 2025-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_inspector_app', '0006_trainingdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=32)),
                ('species', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'allowed genus/species',
                'verbose_name_plural': 'Classes used for training',
            },
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='knownspecies',
            options={'verbose_name_plural': 'Known Species'},
        ),
        migrations.AlterModelOptions(
            name='trainingdatabase',
            options={'verbose_name': 'training entry', 'verbose_name_plural': 'Training Database'},
        ),
    ]
